apiVersion: v1
kind: Service
metadata:
  name: authService
spec:
  selector:
    app: authService
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 31000
  type: NodePort
