apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyer
  labels:
    app: buyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyer
  template:
    metadata:
      labels:
        app: buyer
    spec:
      containers:
        - name: buyer
          image: dinukakariyawasam/ayurveda:buyer
          ports:
            - containerPort: 3002
