apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyer
  labels:
    app: buyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyer
  template:
    metadata:
      labels:
        app: buyer
    spec:
      containers:
        - name: buyer
          image: dinukakariyawasam/ayurveda:buyer
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: buyer
spec:
  selector:
    app: buyer
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 31000
  type: NodePort

